# Generated by Django 5.0.6 on 2024-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
