# Generated by Django 5.0.6 on 2024-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_todos_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
